#!/bin/bash

START=$(date +%s%N)
firefox -new-instance -headless -screenshot -purgecaches -private $1 2>&1 1>/dev/null
END=$(date +%s%N)
TIME=$(echo "($END - $START) / 1000000" | bc)

THRESHOLD=5000
if [[ $2 ]]
then
THRESHOLD=$2
fi

echo -e "Time:\t\t$TIME ms\nThreshold:\t$THRESHOLD ms\nDifference:\t$((TIME - THRESHOLD)) ms"

if [ "$TIME" -gt "$THRESHOLD" ]
then
exit 1
fi

exit 0